version: '3'
services:
  test-db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'unsafe_password'
      POSTGRES_DB: 'zio_template'
